//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PL_MVC.ServiceMateria {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceMateria.IMateriaService")]
    public interface IMateriaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMateriaService/Add", ReplyAction="http://tempuri.org/IMateriaService/AddResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Semestre))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Result))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Materia))]
        ML.Result Add(ML.Materia materia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMateriaService/Add", ReplyAction="http://tempuri.org/IMateriaService/AddResponse")]
        System.Threading.Tasks.Task<ML.Result> AddAsync(ML.Materia materia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMateriaService/GetAll", ReplyAction="http://tempuri.org/IMateriaService/GetAllResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Semestre))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Result))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Materia))]
        ML.Result GetAll(ML.Materia materia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMateriaService/GetAll", ReplyAction="http://tempuri.org/IMateriaService/GetAllResponse")]
        System.Threading.Tasks.Task<ML.Result> GetAllAsync(ML.Materia materia);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMateriaServiceChannel : PL_MVC.ServiceMateria.IMateriaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MateriaServiceClient : System.ServiceModel.ClientBase<PL_MVC.ServiceMateria.IMateriaService>, PL_MVC.ServiceMateria.IMateriaService {
        
        public MateriaServiceClient() {
        }
        
        public MateriaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MateriaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MateriaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MateriaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ML.Result Add(ML.Materia materia) {
            return base.Channel.Add(materia);
        }
        
        public System.Threading.Tasks.Task<ML.Result> AddAsync(ML.Materia materia) {
            return base.Channel.AddAsync(materia);
        }
        
        public ML.Result GetAll(ML.Materia materia) {
            return base.Channel.GetAll(materia);
        }
        
        public System.Threading.Tasks.Task<ML.Result> GetAllAsync(ML.Materia materia) {
            return base.Channel.GetAllAsync(materia);
        }
    }
}
